name: Newsletter Studio
current_version: 16.0.0
version_groups:  
  - name: Umbraco 17
    versions:
    - version: 17.0.0
  - name: Umbraco 16
    versions:
    - version: 16.0.0
  - name: Umbraco 15
    versions:
    - version: 15.0.0
  - name: Umbraco 14
    versions:
    - version: 14.0.0
  - name: Umbraco 13
    versions:
    - version: 13.0.0
  - name: Umbraco 12
    versions:
    - version: 12.1.0
    - version: 12.0.0
  - name: Umbraco 11
    versions:
    - version: 11.0.0
  - name: Umbraco 10
    versions:
    - version: 10.0.0
  - name: Umbraco 9
    versions:
    - version: 4.0.0
  - name: Umbraco 8
    versions:
    - version: 3.0.0    
